server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location /api/ {
    proxy_pass http://prod-backend:8080/;
    include /etc/nginx/conf.d/common.conf;
  }

  location /ai/ {
    proxy_pass http://prod-ai:8000/;
    include /etc/nginx/conf.d/common.conf;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
