spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3307/iportfolio?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6380}
      password: ${REDIS_PASSWORD}

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5673}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration

  jwt:
    access_secret: ${JWT_ACCESS_SECRET}
    refresh_secret: ${JWT_REFRESH_SECRET}

oauth:
  frontend-callback-uri: ${FRONTEND_OAUTH_CALLBACK_URI:}
  frontend-logout-callback-uri: ${FRONTEND_OAUTH_LOGOUT_CALLBACK_URI:}
  kakao:
    client-id: ${KAKAO_CLIENT_ID:}
    client-secret: ${KAKAO_CLIENT_SECRET:}
    redirect-uri: ${KAKAO_REDIRECT_URI:}
    logout-redirect-uri: ${KAKAO_LOGOUT_REDIRECT_URI:}
